# Site settings
title: Vienna RSS | The Free and Open Source RSS/Atom Reader for Mac OS X
email: your-email@domain.com
description: The Free and Open Source RSS/Atom Reader for Mac OS X
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ViennaRSS
github_username:  ViennaRSS

# Build settings
markdown: kramdown
